// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rongpengju/delivery_problem/internal/biz"
	"github.com/rongpengju/delivery_problem/internal/data"
	"github.com/rongpengju/delivery_problem/internal/pkg/etc"
)

// Injectors from wire.go:

func initEntrypoint() (*Entrypoint, error) {
	config, err := newConfig()
	if err != nil {
		return nil, err
	}
	courier := biz.NewCourier(config)
	database, err := data.NewDatabase()
	if err != nil {
		return nil, err
	}
	entrypoint := NewEntrypoint(config, courier, database)
	return entrypoint, nil
}

// wire.go:

type Entrypoint struct {
	Config  *etc.Config
	Courier *biz.Courier
	DB      *data.Database
}

func NewEntrypoint(config *etc.Config, courier *biz.Courier, db *data.Database) *Entrypoint {
	return &Entrypoint{
		Config:  config,
		Courier: courier,
		DB:      db,
	}
}
